on:
  release:
    types: [created]
name: release
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: pack
        uses: mohuishou/utools/.github/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $ {{ github.ref }}
          dir: ./build
          upload_url: ${{ github.event.release.upload_url }}
